jenkins:
  systemMessage: "Welcome to your new Jenkins Controller, ejnoy!"
  numExecutors: 0
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "password"
        - id: "dev"
          password: "password"
        - id: "dev2"
          password: "password"

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "Authenticated_Devs"
            description: "Authenticated Devs"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Configure"
              - "Job/Build"
              - "Job/Workspace"
              - "Agent/Build"
              - "Agent/Connect"
              - "Agent/Build"
              - "Agent/Disconnect"

            assignments:
              - "authenticated"

# Setting up Agents 
  nodes:
    - permanent:
        labelString: "Master_Agent master_agent"
        mode: NORMAL
        name: "Master_Agent"
        numExecutors: 1
        remoteFS: "/home/ubuntu/j_agent"
        launcher:
          ssh:
            host: '172.31.5.6'
            port: 22
            credentialsId: ssh-Master-Controller
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false

# Set up credentials
credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "ssh-Master-Controller"
              username: ubuntu
              description: "SSH passphrase with private key file. Private key provided"
              privateKeySource:
                directEntry:
                  privateKey: "${readFile:${SSH_PRIVATE_FILE_PATH}}"
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "ssh-GitHub"
              username: Inframous
              description: "SSH Private Key for Git (Same one)"
              privateKeySource:
                directEntry:
                  privateKey: "${readFile:${SSH_PRIVATE_FILE_PATH}}"
          - aws:
              scope: GLOBAL
              id: "aws-Master-Controller"
              accessKey: '<aws_access_key_id>'
              secretKey: '<aws_secret_access_key>'
              description: "AWS Credentials"

# Testing this block
unclassified:
  location:
    adminAddress: "EMAIL_ADDRESS"
    url: "<CONTROLLER_IP>"

## End block

jobs:
  - file: /var/jenkins_home/pipelines/import_depInfra.groovy
  - file: /var/jenkins_home/pipelines/import_desInfra.groovy

security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "AcceptFirstConnectionStrategy"
  scriptApproval:
    approvedScriptHashes:
      - "SHA512:338c9e36cf31f0ee8bc4a70563e207585e8cdd5207f4e7da8cf3245336e5cee1157d475fa05c81a555c2df7d83c76b2acc0fd1ba4ce51f73556609c24915c6c3"
      - "SHA512:4419eea5b274d8a5034fdb22a1052789398a55739a0c402aac635c24a2a900f9d9279c03c8390b5dc44be20a41c84e3a944063cce9eac48ba568c5117dc2ef5a"
      - "SHA512:4fd8163e075b17bf51fb120b3fb1d3e32565d72b9a227fe1fc95f5004e92a9e9da25516c82f4b699d6162878ac09de14df359206d6f08908108ae8fb44281f62"
      - "SHA512:7248bcdff1771718f8a87c6872be317f3e9dbdba73ed39ad20afe2794a19b88cdba71d40a4aa7d23c694af127f6fda776481ded886f07cb46c0ad58eb5c15589"





